trigger:
  - main

pool:
  name: 'flxbuilder'

variables:
  azureSubscription: 'FLX'
  appName: 'flxstore'
  resourceGroup: 'FLX-TEST'
  nodeVersion: '20.x'
  artifactFeedName: 'FLXSTOREPACKAGES'  # Updated feed name
  universalPackageName: '$(appName)'

stages:
# -----------------------------
# BUILD STAGE
# -----------------------------
- stage: Build
  displayName: 'Build Application'
  jobs:
  - job: Build
    displayName: 'Build Node.js App'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '$(nodeVersion)'
      displayName: 'Install Node.js'

    - script: |
        npm ci
      displayName: 'Install dependencies'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true
      displayName: 'Archive files'

    # ✅ Publish ZIP as Universal Package to FLXSTOREPACKAGES feed
    - task: UniversalPackages@0
      displayName: 'Publish Deployment Package to FLXSTOREPACKAGES Feed'
      inputs:
        command: 'publish'
        publishFeed: '$(System.TeamProject)/$(artifactFeedName)'
        packageName: '$(appName)'
        publishDirectory: '$(Build.ArtifactStagingDirectory)'
        version: '$(Build.BuildId)'

# -----------------------------
# DEPLOY STAGE
# -----------------------------
- stage: Deploy
  displayName: 'Deploy to Azure App Service'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: Deploy
    displayName: 'Deploy to Azure'
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          # ✅ Download package from FLXSTOREPACKAGES feed
          - task: UniversalPackages@0
            displayName: 'Download Package from FLXSTOREPACKAGES Feed'
            inputs:
              command: 'download'
              downloadFeed: '$(System.TeamProject)/$(artifactFeedName)'
              packageName: '$(universalPackageName)'
              version: '$(Build.BuildId)'
              downloadPath: '$(Pipeline.Workspace)/feed_download'

          # ✅ Deploy downloaded package to Azure App Service
          - task: AzureWebApp@1
            inputs:
              azureSubscription: '$(azureSubscription)'
              appName: '$(appName)'
              package: '$(Pipeline.Workspace)/feed_download/$(Build.BuildId).zip'
              deploymentMethod: 'auto'
            displayName: 'Deploy to Azure App Service'

          # ✅ Configure App Settings securely via Key Vault
          - task: AzureAppServiceSettings@1
            inputs:
              azureSubscription: '$(azureSubscription)'
              appName: '$(appName)'
              resourceGroupName: '$(resourceGroup)'
              appSettings: |
                [
                  {
                    "name": "KEY_VAULT_URL",
                    "value": "@Microsoft.KeyVault(SecretUri=https://flxlock.vault.azure.net/secrets/KEY-VAULT-URL/)",
                    "slotSetting": false
                  },
                  {
                    "name": "STORAGE_ACCOUNT_NAME",
                    "value": "@Microsoft.KeyVault(SecretUri=https://flxlock.vault.azure.net/secrets/STORAGE-ACCOUNT-NAME/)",
                    "slotSetting": false
                  },
                  {
                    "name": "CONTAINER_NAME",
                    "value": "@Microsoft.KeyVault(SecretUri=https://flxlock.vault.azure.net/secrets/CONTAINER-NAME/)",
                    "slotSetting": false
                  },
                  {
                    "name": "STORAGE_ACCOUNT_KEY",
                    "value": "@Microsoft.KeyVault(SecretUri=https://flxlock.vault.azure.net/secrets/STORAGE-ACCOUNT-KEY/)",
                    "slotSetting": false
                  },
                  {
                    "name": "STORAGE_KEY_SECRET_NAME",
                    "value": "@Microsoft.KeyVault(SecretUri=https://flxlock.vault.azure.net/secrets/STORAGE-KEY-SECRET-NAME/)",
                    "slotSetting": false
                  },
                  {
                    "name": "NODE_ENV",
                    "value": "production",
                    "slotSetting": false
                  },
                  {
                    "name": "PORT",
                    "value": "8080",
                    "slotSetting": false
                  }
                ]
            displayName: 'Configure App Settings'
